CREATE DATABASE;
USER_ID DISTINCT:(INT);

-- @block 
CREATE DATABASE Yahway_Database;

-- @block
USE Yahway_Base;

-- @block
CREATE TABLE User Infromatiom \ (
    ID INT UNIQUE , 
    Age INT,
    Gender VARCHAR,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Country VARCHAR(255) NOT NULL
);

-- @block
CREATE TABLE User_Data (
    CURHCH_ID INT UNIQUE , 
    ADMIN_EMAIL VARCHAR(255) NOT NULL,
    ADMIN_PASSWORD VARCHAR(255) NOT NULL,
    ADMIN_PHONE VARCHAR(255) NOT NULL,
    ADMIN_COUNTRY VARCHAR(255) NOT NULL,
);