CREATE DATABASE;
USER_ID DISTINCT:(INT);

-- @block 
CREATE DATABASE Yahway_Database;

-- @block
USE Yahway_Base;

-- @block
CREATE TABLE User Infromatiom \ (
    ID INT UNIQUE , 
    Age INT,
    Gender VARCHAR,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Country VARCHAR(255) NOT NULL
);

-- @block
CREATE TABLE Church_Data (
    CURHCH_ID INT UNIQUE , 
    ADMIN_EMAIL VARCHAR(255) NOT NULL,
    ADMIN_PASSWORD VARCHAR(255) NOT NULL,
    ADMIN_PHONE VARCHAR(255) NOT NULL,
    ADMIN_COUNTRY VARCHAR(255) NOT NULL,
);

-- @block
CREATE TABLE Store_Data (
    STORE_ID INT UNIQUE , 
    STORE_NAME VARCHAR(255) NOT NULL,
    STORE_ADDRESS VARCHAR(255) NOT NULL,
    STORE_PHONE VARCHAR(255) NOT NULL,
    STORE_COUNTRY VARCHAR(255) NOT NULL,
    STORE_ITEM VARCHAR(255) NOT NULL,
    STORE_ITEM_ID INT UNIQUE , 
    STORE_PRICE VARCHAR(255) NOT NULL,
    STORE_QUANTITY VARCHAR(255) NOT NULL,
    STORE_DESCRIPTION VARCHAR(255) NOT NULL,
    STORE_IMAGE VARCHAR(255) NOT NULL,
    STORE_STATUS VARCHAR(255) NOT NULL,
    STORE_CATEGORY VARCHAR(255) NOT NULL,
    STORE_SUBCATEGORY VARCHAR(255) NOT NULL,
    STORE_TAGS VARCHAR(255) NOT NULL,
    STORE_TAGS VARCHAR(255) NOT NULL,
    STORE_TAGS VARCHAR(255) NOT NULL,
    STORE_TAGS VARCHAR(255) NOT NULL,
    

);
